esphome:
  name: bspoolesp32c6
  friendly_name: bsPoolESP32C6
  on_boot:
    priority: 600
    then:
      - output.turn_off: rfSwitch
      - delay:
          100ms
      - output.turn_on: externalAntenna

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  networks:
    - ssid: !secret wifi_ssid_rs
      password: !secret wifi_password_rs
    - ssid: !secret wifi_ssid_main
      password: !secret wifi_password_main


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bspoolesp32C6 Fallback Hotspot"
    password: "12345678"

captive_portal:

# Zapne externí antenu
output:
  - platform: gpio
    pin: GPIO14
    id: externalAntenna
    
  - platform: gpio
    pin: GPIO3
    id: rfSwitch

uart:
  tx_pin: GPIO21
  rx_pin: GPIO1
  baud_rate: 19200
  debug:
    direction: BOTH
    dummy_receiver: false
    #direction: RX
    #dummy_receiver: true
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ':');
#i2c:
#  sda: GPIO22
#  scl: GPIO23
#  scan: true

external_components:
  - source:
      type: git
      url: https://github.com/ondralie/esphome-bspool-chlorinator
    components: [ bs_pool ]

bs_pool:
  update_interval: 15s

sensor:
  - platform: bs_pool
    cell_current:
      name: Cell current
    cell_intensity:
      name: Cell intensity
    cell_voltage:
      name: Cell voltage
    ph:
      name: pH
    salt_concentration:
      name: Salt concentration
    radox:
      name: ORP
    temperature:
      name: Temperature
    hours_of_operation:
      name: Hours of operation
  - platform: wifi_signal
    name: "Pool ESP WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Pool ESP Uptime"
#  - platform: bmp280_i2c
#    temperature:
#      name: "Outside Temperature"
#    pressure:
#      name: "Outside Pressure"
#    address: 0x77
#    update_interval: 60s

button:
  - platform: restart
    name: "Restart ESP"

text_sensor:
  - platform: bs_pool
    time:
      name: Device Time
    version:
      name: Device firmware version
    chlorinator_type:
      name: Chlorinator type
  - platform: wifi_info
    ip_address:
      name: "ESP IP address"

binary_sensor:
  - platform: bs_pool
    alarm_redox_saturated:
      name: ORP probe saturated alarm
    alarm_overtemperature:
      name: Overtemperature inside the chlorinator
    alarm_open_circuit:
      name: Open circuit alarm
    alarm_water_flow:
      name: Lack of water flow alarm
    alarm_short_circuit:
      name: Short circuit alarm
    alarm_unit_stopped:
      name: P954 unit stopped alarm
    alarm_communication_error:
      name: Communication error to P954 alarm
    warning_low_salt:
      name: Too few salt
    warning_high_salt:
      name: Too much salt
    warning_ph_pump_overrun:
      name: pH problem, pump has run for too long
    warning_acid:
      name: Acid warning
    warning_clock_set:
      name: Clock has been set
    warning_probe_disconnected:
      name: ORP or chlorine probe disconnected
    status_output_voltage_polarity:
      name: Polarity of output voltage
    status_filter_pump_running:
      name: Filter pump running
    status_chlorination_process:
      name: Chlorination in process
    status_stopped_by_remote:
      name: Stopped by remote controller
    status_orp_sensor_stable:
      name: ORP sensor reading is stable
    status_salt_sensor_connected:
      name: Salt sensor connected
    status_electrode_cleaning:
      name: Electrode cleaning in process
    status_super_chlorination:
      name: Super-chlorination in process

number:
  - platform: bs_pool
    power:
      name: Power
    pool_volume:
      name: Pool volume
    cleaning_cycle:
      name: Cleaning cycle
    ph_target:
      name: pH target
    orp_target:
      name: ORP target
    relay_delay:
      name: Relay delay
    program_1_start:
      name: Relay program 1 start
    program_1_stop:
      name: Relay program 1 stop
    program_2_start:
      name: Relay program 2 start
    program_2_stop:
      name: Relay program 2 stop

select:
  - platform: bs_pool
    control_mode:
      name: Control mode
    language:
      name: Language
    relay_status:
      name: Relay status

switch:
  - platform: bs_pool
    user_is_outdoor:
      name: Pool is outdoor
    user_cover_switch_off:
      name: Cover switch off
    user_flow_switch_installed:
      name: Flow switch installed
    user_orp_displayed:
      name: ORP displayed
    user_ph_alarm:
      name: pH alarm
    user_ph_corrector_alkaline:
      name: pH corrector alkaline
    user_ph_control:
      name: pH control
    user_cover_installed:
      name: Cover installed
    stop_start:
      name: Chlorinator running
